//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "grid_worlds")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub name: String,
    pub width: i32,
    pub height: i32,
    pub obs_polygons: Json,
    pub version: i32,
    #[sea_orm(has_many)]
    pub plans: HasMany<super::plans::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
