//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
// Eq Derive macro not supported because of Json attribute
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "grid_world_states")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub grid_world_id: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub obs_polygons: Json,
    pub timestamp: DateTimeWithTimeZone,
    pub sequence_id: i32,
    #[sea_orm(
        belongs_to,
        from = "grid_world_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub grids: BelongsTo<super::grid_worlds::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
