//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "plans")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub grid_id: i32,
    pub name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub vertices: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub meta: Json,
    #[sea_orm(
        belongs_to,
        from = "grid_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub grids: BelongsTo<super::grid_worlds::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
