//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
// Eq Derive macro not supported because of Json attribute
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "plan_robots")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub plan_id: i32,
    pub robot_id: i32,
    /// `[x, y]` — where this robot enters this plan.
    #[sea_orm(column_type = "JsonBinary")]
    pub start_vertex: Json,
    /// `[x, y]`, or null for a robot with nowhere in particular to be.
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub goal_vertex: Option<Json>,
    #[sea_orm(
        belongs_to,
        from = "plan_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub plan: BelongsTo<super::plans::Entity>,
    #[sea_orm(
        belongs_to,
        from = "robot_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub robot: BelongsTo<super::robots::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
