//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
// Eq Derive macro not supported because of Json attribute
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "robots")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub capabilities: Json, // json representation for robot capabilities during prototyping
    #[sea_orm(has_many)]
    pub route_plans: HasMany<super::route_plans::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
